base:
  random_state: 42
data:
  dataset_csv: 'data/iris.csv'
  processed_path: 'data/processed.csv'
  features_path: 'data/features.csv'
  trainset_path: 'data/train_iris.csv'
  testset_path: 'data/test_iris.csv'
  test_size: 0.3
  random_state: 42

training:
  clf_params:
    C: [0.01, 0.1, 1, 10, 100]
    solver: ['liblinear', 'saga']
    multi_class: ['auto', 'ovr']
    max_iter: [100, 200, 300]
  model_path: 'model/model.pkl'


reports:
  metrics_file: 'eval/metrics.json'
  confusion_matrix_file: 'eval/confusion_matrix.png'
  confusion_matrix_csv_file: 'eval/confusion_matrix_data.csv'

